# Generated by Django 3.0.14 on 2021-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feauture_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
